service imap-login {
  inet_listener imap {
    port = 143
  }
}

service imap {
}

service auth {
  unix_listener auth-userdb {
    mode = 0666
    user = dovecot
    group = dovecot
  }
}

service dict {
  unix_listener dict {
    mode = 0666
  }
}
