mail_uid = vmail
mail_gid = vmail
mail_privileged_group = vmail
mail_location = maildir:/var/mail/%d/%n/Maildir
namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Sent {
    special_use = \Sent
  }
}
